### ISSUE TITLE
Add support for embedded types

### ISSUE THREAD

**Issue by vincent99** [rancherio/api-ui#2]
{resourceFields: {field: {type: 'anotherType'}}}

![image](https://cloud.githubusercontent.com/assets/753917/5750622/a67f0106-9c14-11e4-8e9e-3bfc1533c9fa.png)

**Comment by vincent99** [comment]
Put in a temporary fix for this by making types show up as a JSON field that you can edit in [v1.0.1](https://github.com/rancherio/api-ui/releases/tag/v1.0.1)

**Comment by deniseschannon** [comment]
Moving issues into rancherio/rancher.

https://github.com/rancherio/rancher/issues/322
